---
title: "CRAN Code"
author: "Yifei Liu"
date: "12/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## David Robinson Analysis
[Video Link](https://www.youtube.com/watch?v=dr4qw8o0nYU&t=8s)

```{r}

library(tidyverse)
library(tidytext)
library(hrbrthemes)
library(ggchicklet) # install.packages("ggchicklet", repos = "https://cinc.rud.is")
theme_set(theme_minimal())


cran_code <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-11-12/loc_cran_packages.csv")

# Or read in with tidytuesdayR package (https://github.com/thebioengineer/tidytuesdayR)
# Either ISO-8601 date or year/week works!
# Install via devtools::install_github("thebioengineer/tidytuesdayR")

cran_code <- tidytuesdayR::tt_load("2019-11-12")
tuesdata <- tidytuesdayR::tt_load(2019, week = 46)

cran_code <- tuesdata$loc_cran_packages


```


what are most common programming langauges in CRAN packages

```{r}
cran_code %>%
  count(language, sort = T) %>%
  head(20) %>%
  mutate(language = fct_reorder(language, n)) %>%
  ggplot(aes(language, n)) +
  geom_col() +
  coord_flip() +
  labs(x = "", y = "# of packages that have codefrom this language")



```


```{r}
by_langauge <- cran_code %>%
  group_by(language) %>%
  summarize(packages = n(),
            files = sum(file),
            comments = sum(comment),
            files_per_pacakge = files / packages,
            code = sum(code),
            lines_per_package = code / packages,
            comment_code_ratio = comments / code) %>%
  arrange(desc(packages))
  
```


```{r}

by_langauge %>%
  head(20) %>%
  mutate(language = fct_reorder(language, packages)) %>%
  ggplot(aes(language, packages)) +
  geom_col() +
  coord_flip() +
  labs(x = "", y = "# of packages that have codefrom this language")


by_langauge %>%
  gather(metric, value, packages, code, files) %>%
  group_by(metric) %>%
  top_n(8, value) %>%
  ungroup() %>%
  mutate(language = reorder_within(language, value, metric)) %>%
  ggplot(aes(language, value)) +
  geom_col() +
  coord_flip() +
  scale_x_reordered() +
  scale_y_continuous(labels = scales::comma) +
  facet_wrap(~ metric, scales = "free", ncol = 1) +
  labs(x = "value (# of liens of code, files, or pacakges)")


```

How much are langauge are commented


```{r}

by_langauge %>%
  filter(packages >= 20) %>%
  ggplot(aes(packages, comment_code_ratio)) +
  geom_text(aes(label = language), check_overlap = T, vjust = 1, hjust = 1) +
  geom_point() +
  scale_x_log10() +
  expand_limits(x = 10) +
  labs(x = "# of pacakges language is used in",
       y = "Comment/Code Ratio")

```

```{r}

by_langauge %>%
  filter(packages >= 20) %>%
  ggplot(aes(packages, lines_per_package)) +
  geom_text(aes(label = language), check_overlap = T, vjust = 1, hjust = 1) +
  geom_point() +
  scale_x_log10() +
  expand_limits(x = 10) +
  labs(x = "# of pacakges language is used in",
       y = "Lines Per Package")

```

How much R code is there in each pacakge

PS: log scale is new norm

```{r}

cran_code %>%
  filter(language == "R") %>%
  ggplot(aes(code)) +
  geom_histogram() +
  scale_x_log10(labels = scales::comma)
```



```{r}

cran_code %>%
  filter(language == "R") %>%
  arrange(desc(code)) %>%View()

```



let's just look at tidyverse pacakges

```{r}

packages <- tidyverse::tidyverse_packages() %>%
  str_extract("[a-z\\d]+")

cran_code %>%
  filter(pkg_name %in% packages) %>%
  mutate(pkg_name = fct_reorder(pkg_name, code, sum),
         language = fct_lump(language, 6),
         language = fct_reorder(language, code, sum, .desc = F)) %>%
  ggplot(aes(pkg_name, code, fill = language)) +
  geom_chicklet(width = 0.75) +
  coord_flip() +
  ggthemes::scale_fill_tableau("Tableau 20", name = NULL) +
  theme_ipsum_rc(grid="X") +
  guides(fill = guide_legend(reverse = T)) +
  theme(axis.text.x = element_text(color = "gray60", size = 10),
        legend.position = "bottom")

```


```{r}
cran_code %>%
  filter(pkg_name %in% packages) %>%
  filter(language == "R") %>%
  mutate(comment_code_ratio = comment / code) %>%
  arrange(desc(comment_code_ratio))


```

```{r}

cran_code %>%
  filter(language == "R", code >= 100) %>%
  mutate(tidyverse = ifelse(pkg_name %in% packages, "Tidyverse", "Other")) %>%
  ggplot(aes(code / comment)) +
  geom_histogram() +
  scale_x_log10(labels = scales::number_format(accuracy = 1)) +
  facet_wrap(~ tidyverse, ncol = 1, scales = "free_y") +
  labs(x = "Code / Comment ratio")
  


```

```{r}

cran_code %>% 
  filter(code >= 100, language == "R", comment > 0) %>%
  mutate(code_comment_ratio = code / comment) %>%
  arrange(desc(code_comment_ratio))

```



```{r}

pkgs <- available.packages()

pkgs %>%
  as_tibble()

# take package download from 2019-12-19, further details on https://github.com/r-hub/cranlogs

pacakge_downloads <- read_csv("http://cran-logs.rstudio.com/2019/2019-12-19.csv.gz")
```

```{r}

downloads_by_pacakges <- pacakge_downloads %>%
  distinct(package, ip_id) %>%
  count(pkg_name = package, sort = T, name = "downloads")

```

```{r}

cran_code %>%
  filter(language == "R") %>%
  inner_join(downloads_by_pacakges, by = "pkg_name") %>%
  arrange(desc(downloads)) %>%
  filter(downloads >= 100) %>%
  ggplot(aes(downloads, code)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()

cran_code %>%
  filter(language == "R") %>%
  inner_join(downloads_by_pacakges, by = "pkg_name")

```


```{r}

package_metadata <- available.packages() %>%
  as_tibble() %>%
  janitor::clean_names() %>%
  select(-version, -file)


cran_code %>%
  filter(language == "R") %>%
  inner_join(package_metadata, by = c(pkg_name = "package")) %>%
  mutate(license = fct_lump(license, 10),
         license = fct_reorder(license, code)) %>%
  ggplot(aes(license, code)) +
  geom_boxplot() +
  coord_flip() +
  scale_y_log10()

n_import <- package_metadata %>%
  select(package, imports) %>%
  separate_rows(imports, sep = ",") %>%
  extract(imports, "import", "([A-Za-z\\d\\.]+)") %>%
  filter(!is.na(import)) %>%
  count(import, sort = T, name = "n_reverse_import")
```



```{r}
cran_code %>%
  filter(language == "R") %>%
  left_join(n_import, by = c(pkg_name = "import")) %>%
  replace_na(list(n_reverse_import = 0)) %>%
  filter(n_reverse_import >= 10) %>%
  ggplot(aes(n_reverse_import, code)) +
  geom_point() +
  geom_text(aes(label = pkg_name), vjust = 1, hjust = 1, check_overlap = T) +
  scale_x_log10() + 
  scale_y_log10()

```

## my own analysis

network analysis, try to figure out which package is the most import one, I guess. 












