---
title: "The Office ratings and scripts analysis"
author: "Yifei Liu"
date: "3/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

load packages
```{r}
library(tidyverse)
library(schrute)
library(ggrepel)
library(tidytext)
library(glmnet)
detach("package:dplyr", unload = TRUE)
library(dplyr)
theme_set(theme_minimal())

office_transcripts <- as_tibble(theoffice) %>%
  mutate(season = as.integer(season),
         episode = as.integer(episode)) %>%
  mutate(character = str_remove_all(character, '"'))  %>%
  mutate(name = str_to_lower(str_remove(episode_name, "\\.| \\(Part.*"))) 


office_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-17/office_ratings.csv') %>%
  mutate(name = str_to_lower(str_remove(title, "\\.| \\(Part.*|\\: Part.*")))
```


```{r}
# check average rating cross all seasons
office_ratings %>%
  group_by(season) %>%
  summarize(average_rating = mean(imdb_rating)) %>%
  ggplot(aes(season, average_rating)) +
  geom_line() +
  scale_x_continuous(breaks = 1:9)

x <- office_ratings %>%
  mutate(title = fct_inorder(title),
         episode_number = row_number())

x %>%
  ggplot(aes(episode_number, imdb_rating)) +
  geom_line() +
  geom_smooth() +
  geom_point(aes(color = factor(season), size = total_votes)) +
  geom_text_repel(aes(label = title), data = x  %>% filter(imdb_rating > 9.2)) +
  theme(axis.text.x = element_blank(),
        legend.position = "none") +
  labs(x = "Episode number",
       y = "IMDB ratings",
       title = "Popularity of the Office episodes over time",
       subtitle = "Color represent season, size represent # of ratings") +
  expand_limits(x = -5, y = 10)

```



```{r}

office_ratings %>%
  arrange(desc(imdb_rating)) %>%
  mutate(title = paste0(season, ".", episode, " ", title),
         title = fct_reorder(title, imdb_rating)) %>%
  head(20) %>%
  ggplot(aes(title, imdb_rating, color = factor(season), size = total_votes)) +
  geom_point() +
  coord_flip() +
  labs(color = "Season",
       title = "Most popular episodes of The Office")

```

### Transcripts



```{r}

blacklist <- c("year", "hey", "uh", "gonna")
blacklist_character <- c("Everyone", "All", "Both", "Guy", "Girl", "Group")

transcript_words <- office_transcripts %>%
  group_by(character) %>%
  filter(n() >= 100,
         n_distinct(episode) > 2) %>%
  ungroup() %>%
  select(-text_w_direction) %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words, by = "word") %>%
  filter(!word %in% blacklist,
         !character %in% blacklist_character)

# check are there word specific to inidividual character

character_tf_idf <- transcript_words %>%
  add_count(word) %>%
  filter(n > 20) %>%
  count(word, character) %>%
  bind_tf_idf(word, character, n) %>%
  arrange(desc(tf_idf))

```


```{r}

character_tf_idf %>%
  filter(character %in% c("Dwight", "Jim", "Michael", "Darryl", "David Wallace", "Jan")) %>%
  group_by(character) %>%
  top_n(10, tf_idf) %>%
  ungroup() %>%
  mutate(word = reorder_within(word, tf_idf, character)) %>%
  ggplot(aes(word, tf_idf)) +
  geom_col() +
  coord_flip() +
  scale_x_reordered() +
  facet_wrap(~ character, scales = "free_y") +
  labs(x = "",
       y = "TF-IDF of character-word pairs")

```


### Machine learning

What affect the popularity of an episode:

* season
* Director
* Writter
* Lines per character


```{r}

office

ratings_summarized <- office_ratings %>%
  group_by(name) %>%
  summarize(imdb_rating = mean(imdb_rating))
  
character_lines_ratings <- office_transcripts %>%
  filter(!character %in% blacklist_character) %>%
  count(character, name) %>%
  group_by(character) %>%
  filter(sum(n) >= 50,
         n() > 3) %>%
  inner_join(ratings_summarized, by = "name") 


character_lines_ratings %>%
  summarize(avg_rating = mean(imdb_rating),
           nb_episodes = n()) %>%
  arrange(desc(avg_rating))
  

```

```{r}

director_writer_features <- office_transcripts %>%
  distinct(name, director, writer) %>%
  gather(type, value, director, writer) %>%
  separate_rows(value, sep = ";") %>%
  unite(feature, type, value, sep= ": ") %>%
  add_count(feature) %>%
  filter(n >= 3) %>%
  mutate(value = 1) %>%
  ungroup()

character_line_features <- character_lines_ratings %>% 
  ungroup() %>%
  transmute(name, feature = character, value = log2(n))
  

season_features <- office_ratings %>%
  distinct(name, season) %>%
  transmute(name, feature = paste("season:", season), value = 1)

features <- bind_rows(director_writer_features, character_line_features, season_features) %>%
  semi_join(office_ratings, by = "name") %>%
  semi_join(office_transcripts, by = "name")


```


```{r}

episode_feature_matrix <- features %>%
  cast_sparse(name, feature, value) 

ratings <- ratings_summarized$imdb_rating[match(rownames(episode_feature_matrix), ratings_summarized$name)]


mod <- cv.glmnet(episode_feature_matrix, ratings)
plot(mod)

tidy(mod$glmnet.fit) %>%
  filter(lambda == mod$lambda.min,
         term != "(Intercept)") %>%
  mutate(term = fct_reorder(term, estimate)) %>%
  ggplot(aes(term, estimate, fill = estimate > 0)) +
  geom_col() +
  coord_flip() +
  labs(x = "Estimated effect on the rating of an episode") +
  theme(legend.position = "none")
```


















