---
title: "Uncanny X-men"
author: "Yifei Liu"
date: "7/2/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


[David Robinson Analysis](https://www.youtube.com/watch?v=NY0-IFet5AM)


```{r}

library(tidyverse)
theme_set(theme_minimal())
characters <- tidytuesdayR::tt_load(2018, week = 9)$week9_comic_characters
xmen <- tidytuesdayR::tt_load('2020-06-30')


```


```{r}

character_visualization <- xmen$character_visualization %>%
  separate(character, c("superhero", "secret_identity"), sep = " = ", fill = "right")

```

```{r}
library(ggrepel)
by_character <- character_visualization %>%
  group_by(superhero) %>%
  summarize(across(speech:depicted, 
                   list(total = sum, 
                        issues = ~sum(.>0),
                        avg = ~ mean(.[depicted > 0]))))

by_character %>%
  arrange(desc(speech_issues)) %>%
  filter(speech_issues > 0) %>%
  head(25) %>%
  mutate(superhero = fct_reorder(superhero, speech_issues)) %>%
  ggplot(aes(speech_issues, superhero))  +
  geom_col() +
  labs(title = "Which X-men appeared in the most issue?",
       y = "# of issues")

by_character %>%
  ggplot(aes(depicted_issues, speech_avg))+
  geom_point() +
  geom_text_repel(aes(label = superhero)) +
  labs(x = "# of issues in which character appear",
       y = "Average line per issue depicated") +
  expand_limits(y = 0)

by_character %>%
  ggplot(aes(depicted_issues, thought_avg))+
  geom_point() +
  geom_text_repel(aes(label = superhero)) +
  scale_x_log10() +
  labs(x = "# of issues in which character appears",
       y = "Average thoughts per issue") +
  expand_limits(y = 0)


# Questions: which characters think more and which one speak more?

by_character %>% 
  ggplot(aes(depicted_issues, speech_avg / thought_avg)) +
  geom_point() +
  geom_text_repel(aes(label = superhero)) +
  expand_limits(y = 1) +
  scale_y_log10(breaks = c(1, 3, 10, 30),
                labels = c("Same", "3X", "10X", "30X")) +
  labs(x = "# of issues depicted",
       y = "Speech to thought ratio (log scale)",
       title = "Which X-Mne think, and which speak")

```



```{r}

by_character_costume <- character_visualization %>%
  group_by(superhero, costume) %>%
  summarize(across(speech:depicted, 
                   list(total = sum, 
                        issues = ~sum(.>0),
                        avg = ~ mean(.[depicted > 0])))) %>%
  ungroup() %>%
  mutate(speech_thought_ratio = speech_avg / thought_avg)

by_character_costume %>%
  mutate(superhero = fct_reorder(superhero, speech_total)) %>%
  filter(speech_avg > 0) %>%
  ggplot(aes(speech_avg,
             superhero,
             color = costume, 
             size = depicted_issues)) +
  geom_point() +
  labs(x = "# of lines (in/out of costume)")

costume_ratios <- by_character_costume %>%
  filter(speech_total > 0) %>%
  group_by(superhero) %>%
  summarize(costume_ratio = speech_total[1] / speech_total[2])  %>%
  inner_join(by_character, by = "superhero")

costume_ratios %>%
  ggplot(aes(depicted_issues,
             costume_ratio)) +
  geom_point() +
  geom_text_repel(aes(label = superhero)) +
  scale_y_log10() +
  labs(y = "Lines in costume / Lines out of costume",
        x = "Total issues depcited")


costume_ratios %>%
  mutate(superhero = fct_reorder(superhero, costume_ratio)) %>%
  ggplot(aes(costume_ratio, y = superhero))+
  geom_errorbarh(aes(xmin = 1, xmax = costume_ratio), height = 0) +
  geom_point(aes(size = speech_total, color = costume_ratio > 1)) +
  scale_x_log10()+
  scale_color_discrete(guide = F)+
  labs(size = "# of lines",
       x = "Lines in costume / lines out of costume",
       title = "which character tend to speak in costume/out of character",
       y = "")
```


```{r}
xmen$comic_bechdel %>%
  bind_rows(
```





```{r}
xmen$xmen_bechdel %>% mutate(writer = "Chris Claremont")) %>%
  filter(!is.na(pass_bechdel),
         !is.na(writer)) %>%
  group_by(writer = fct_lump(writer, 4)) %>%
  summarize(n_issues = n(),
            pct_bechdel = mean(pass_bechdel == "yes")) %>%
  arrange(desc(n_issues))

```


```{r}
xmen$xmen_bechdel %>%
  filter(!is.na(pass_bechdel)) %>%
  group_by(issue_group = 20 * (issue %/% 20)) %>%
  summarize(pct_bechdel = mean(pass_bechdel == "yes"),
            n = n()) %>%
  ggplot(aes(issue_group, pct_bechdel)) +
  geom_line()
``` 












